### ISSUE TITLE
mdns is not in the default tasmota configuration

### ISSUE THREAD

**Issue by BrianGilbert** [tim-hellhake/tasmota-adapter#1]
I was investigating this and asking questions in the Tasmota Discord and found that mdns needs to be enabled and compiled into Tasmota by the user

**Comment by tim-hellhake** [comment]
I'm using the latest version `7.1.2` of the firmware.
The support for mDNS is included in the firmware, but it's disabled by default.
The [README.md](https://github.com/tim-hellhake/tasmota-adapter/blob/master/README.md) describes how to activate it.
However, I'm planning to add MQTT support as well.
Which tasmota devices are you currently using?

**Comment by BrianGilbert** [comment]
I was only looking at this as ESPHome support isn't in WebThings Gateway yet, but it appeasr there is a low sucess rate to switch from ESPHome to Tasmota firmware via OTA, so I really hope your planning to populate the empty repo you have for ESPHome? :)

**Comment by tim-hellhake** [comment]
> so I really hope your planning to populate the empty repo you have for ESPHome

That was the plan 😬

**Comment by tim-hellhake** [comment]
I added an issue for the MQTT support: #3.
I'm closing this now.
