### ISSUE TITLE
Sonoff/ Tasmota TH10 -Sonoff TH Sensor Si7021	

### ISSUE THREAD

**Issue by Catalin84** [tim-hellhake/tasmota-adapter#10]
Hi is there a chance that you can make this device sensor with Webthings?
Now the device TH10 flashed with Tasmota works with Websthings but dosent get the values of the temperature and humidity sensor.
The Sensor i use is SONOFF SI7021

**Comment by tim-hellhake** [comment]
Sure, I'll see what I can do!
But I would need you to test it as I don't have the sensors.

**Comment by Catalin84** [comment]
I will test it as much as you need. It will be a good thing for us.
Just let me know when you need me. I have a few days off !

**Comment by Catalin84** [comment]
![image](https://user-images.githubusercontent.com/57527589/74014042-83993780-4996-11ea-9a0e-8e4daabfceb1.png)
I guess the temp/hum sensor is discovered as LED! i have only 2 sonoff flashed with tasmota. One is basic and one TH10/16 with sensor. ON/OFF are working on both but on discovery finds LED like i said maybe is the sensor!

**Comment by tim-hellhake** [comment]
I tried to use the following template: https://templates.blakadder.com/sonoff_TH.html.

> Just select module Sonoff TH (4) and under GPIO14 configure the sensor you have connected.

Unfortunately, `Sonoff TH` is not available in the drop-down menu.
Do you have the standard firmware?
Could you please open `http://[device]/?m=1` for me and send me the output?

**Comment by Catalin84** [comment]
hello this is what i have
{t}{s}SI7021 Temperature{m}23.9°C{e}{s}SI7021 Humidity{m}43.2%{e}{t}OFF

**Comment by Catalin84** [comment]
![image](https://user-images.githubusercontent.com/57527589/76681342-a7394880-65fa-11ea-967f-f42e4832a4c7.png)

**Comment by tim-hellhake** [comment]
If you are on version `0.9.0` of the addon there should be an option for temperature support in the settings of the addons.
After that, the device should have a temperature property.

**Comment by Catalin84** [comment]
Well all i can say is that is working:)
![image](https://user-images.githubusercontent.com/57527589/76684369-44ed4180-6614-11ea-8d63-93b325a1fb39.png)
Thanks! i will test it for more and i can close the issue:)

**Comment by tim-hellhake** [comment]
> Well all i can say is that is working

Nice!

> i can close the issue

Humidity support is still missing.
I would suggest you wait until added it.

**Comment by Catalin84** [comment]
It will be an update for it soon?

**Comment by tim-hellhake** [comment]
I think I will add support for it today but it may take a day until the update is approved.

**Comment by Catalin84** [comment]
Great, i will wait and i will come back with a feedback! Thank you for your hard work!

**Comment by tim-hellhake** [comment]
As soon as the PR is merged you can test the new update.

**Comment by Catalin84** [comment]
![image](https://user-images.githubusercontent.com/57527589/76700067-3d817300-66bc-11ea-93cc-36ac3f4c7730.png)
All working perfect! i see that if i reset the homebridge it dosent connect to devices. i changed from http://ip   to normal ip and is ok.  I will come back later with other issues if they are. But for the moment i will close it. So ! ALL GOOD!
