### ISSUE TITLE
RGBW light support

### ISSUE THREAD

**Issue by off-my-lawn** [tim-hellhake/tasmota-adapter#11]
I have an RGBW light (Mirabella Genio brand) flashed with tasmota 8.1.

Three result of the 'Template' command is.
16:12:32 RSL: stat/tasmota/RESULT = {"NAME":"GenioBulbRGB","GPIO":[255,255,255,255,37,40,255,255,38,255,39,255,255],"FLAG":15,"BASE":18}

On a brief investigation into the code in src/tasmota-adapter.ts

          const response = await getStatus(host, password, 'Color');
          ...
          if (result.Color && result.Color.length == 6
          {
            console.log('Found color device');

While my device returns a length of 8. Two for each available channel.

/cm?cmnd=Color
{"Color":"A63E1200"}

I've also seen reference to RGBWW devices that provide a cool white and warm white option. Although I don't have one of those I assume the length would be 10.

**Comment by tim-hellhake** [comment]
> I've also seen reference to RGBWW devices that provide a cool white and warm white option. Although I don't have one of those I assume the length would be 10.

You are right.
For an RGBWW device, the string would be ten chars long.
I already had plans to add it, but I'm not sure how exactly.
The gateway usually gives you a color picker to control a light bulb, which results in a RGB value.
I don't have the values for the other two channels.
How would you prefer to control them?
I could simply add two new properties to the device, but it wouldn't fit really well into the UI concept of the light bulb.

**Comment by off-my-lawn** [comment]
I'm planning to send you a pull request later today to deal with some of this. (I'm at the start of my work day)

What I have in my branch includes a property for brightness and handles the 4 channel colour globes. Although it doesn't use the white channel when white is requested yet.

I have bought a 2 channel globe that supports the colour temperature property, but haven't managed to get it scanned into the interface yet. The refactored code I'm working on is conditionally adding properties based on what I think are supported.

PS. I'm normally a C++ application developer, I'm dealing with a slight learning curve here.

**Comment by tim-hellhake** [comment]
Version `0.4.5` is out now.
Can you please check if everything works fine?

**Comment by off-my-lawn** [comment]
Yes it's working.

I did notice a little strange behaviour when turning off. The (mobile) UI showed it changing state 3 times. Nothing bad though.

I will say it's a bit of a shame about the brightness. On the mobile UI I only get to choose from 7 full brightness and black. If I care enough I'll find the team doing a webpage and submit an issue there.

**Comment by tim-hellhake** [comment]
@mrstegeman is currently working on an issue that might include the BrightnessProperty mozilla-iot/gateway#2425.

**Comment by tim-hellhake** [comment]
I'm still not sure why the ` Power` command is working for you.
Maybe it's device-specific.

> The (mobile) UI showed it changing state 3 times.

I created a new issue for this: https://github.com/tim-hellhake/tasmota-adapter/issues/13.
I'm closing this now as the light is working.
