### ISSUE TITLE
Support for CT lights

### ISSUE THREAD

**Issue by tim-hellhake** [tim-hellhake/tasmota-adapter#14]

**Comment by off-my-lawn** [comment]
I do have one of these at home flashed and ready to go. Just haven't managed to make the adaptor see it yet. (Yes, I have setoption55 on)

**Comment by tim-hellhake** [comment]
I'll add the option to add them manually: https://github.com/tim-hellhake/tasmota-adapter/issues/15

**Comment by tim-hellhake** [comment]
Update `0.6.1` is out now.
Can you please test if the CT lights work properly?

**Comment by tim-hellhake** [comment]
> Just haven't managed to make the adaptor see it yet

How did you manage to fix it?

**Comment by off-my-lawn** [comment]
For some reason mDNS wasn't enabling even though I repeatedly enabled it. I ended up reflashing the globe and it started working.
