### ISSUE TITLE
Sonoff 4CH oder POW with Temperature/Humidity Sensor

### ISSUE THREAD

**Issue by steko71** [tim-hellhake/tasmota-adapter#19]
Hello Tim,
can you integrate the Sonoff 4CH with Tasmota and temperature sensor at the GPIO in WebThings?
And to display the values of Sonoff POW (voltage / current / power)?
With Domoticz this is not a problem via MQTT. If you can do that WebThings would be a dream ... ;-)
I would like to test it!

Greetings Stefan

**Comment by tim-hellhake** [comment]
Hi @steko71,

I'll try but unfortunately, I have no device to test it with.
Maybe you could give me some details.
What type of sensor are you using?
How do you connect the sensor to the 4CH?
Are the values shown on the web page?
What is the result of the `template` command?

There is an [issue](https://github.com/tim-hellhake/tasmota-adapter/issues/3) for MQTT but so far most of the people seem to use the HTTP transport.

**Comment by steko71** [comment]
Sensor: DS18B20 at GPIO2
![grafik](https://user-images.githubusercontent.com/61690092/75677089-f0001180-5c8a-11ea-945d-e8bab27cbf82.png)

**Comment by tim-hellhake** [comment]
I configured my device with the 4CH template and selected `DS18x20` on `GPIO2` but I still can't see the sensor.
Could you please open http://[device]/?m=1 in your browser and send me the result?

![image](https://user-images.githubusercontent.com/17127122/75720368-ab01cc80-5cd6-11ea-8458-b1477375d48d.png)

**Comment by tim-hellhake** [comment]
> And to display the values of Sonoff POW (voltage / current / power)?

This should already work.
It was added [here](https://github.com/tim-hellhake/tasmota-adapter/issues/5) for the `Koogeek KLUP1`.

If you send me the output of http://[device]/?m=1 of your POW device I could look for differences.

**Comment by steko71** [comment]
4CH: {t}{s}DS18B20 Temperatur{m}25.8°C{e}{t}OFFOFFOFFOFF

POW: {t}{s}Voltage{m}229 V{e}{s}Current{m}0.516 A{e}{s}Power{m}75 W{e}{s}Apparent Power{m}118 VA{e}{s}Reactive Power{m}91 VAr{e}{s}Power Factor{m}0.63{e}{s}Energy Today{m}0.445 kWh{e}{s}Energy Yesterday{m}0.870 kWh{e}{s}Energy Total{m}12.386 kWh{e}{t}ON

**Comment by tim-hellhake** [comment]
Excellent!
Now I can create test cases based on the data.
You have to test it for me, though.

**Comment by steko71** [comment]
thank you, i like to test! ;-)

**Comment by tim-hellhake** [comment]
Ok, that's strange.
I added the data from your sonoff pow to the unit test without creating any test errors.
I'll add some more logs to see what's happening.

**Comment by tim-hellhake** [comment]
It turns out that there is already a lot of logging in place.
Can you please restart the adapter and attach the log to the issue?
I'm searching for something like `Parsed data:`

Is the Sonoff POW working properly besides the missing power stats?

**Comment by steko71** [comment]
Hi Tim,
I updated to 0.7
after that, things that had already been registered could no longer be removed.
So WebThings and Sonoffs flashed again. POW now shows Power / Voltage / Current! Shifting no longer works. When I switch over the Tasmota interface the status is shown in WebThings! Registered things cannot be removed again.

Temperature on the 4CH is not displayed. Only 1 switching channel works. Or is switching only via Hue mode?

Can I actually write in German or directly with you (maybe WhatsApp)? Would be easier and faster ...

**Comment by steko71** [comment]
Do I have to enter the Tasmota IP under "List of device"?

**Comment by tim-hellhake** [comment]
@steko71 
You can contact me via https://chat.mozilla.org.
There is also an `iot` room for the gateway.

**Comment by steko71** [comment]
I'm in the room, how can I write directly with you?

**Comment by tim-hellhake** [comment]
> things that had already been registered could no longer be removed

There are a lot of issues in the gateway repo about this.
Usually rebooting the gateway helps.

> Temperature on the 4CH is not displayed. Only 1 switching channel works. Or is switching only via Hue mode?

Currently, only one channel is supported.
Can you check if you can control the other three channels with the commands `power2`, `power3` and `power4`?

**Comment by tim-hellhake** [comment]
The new update is on the way.
You can activate the support for multiple channels in the settings.

**Comment by tim-hellhake** [comment]
As mentioned in matrix the Sonoff 4CH is now supported.
The temperature sensor is also supported but it seems to have problems with the password protection (https://github.com/tim-hellhake/tasmota-adapter/issues/21).

Additionally, there were two new ideas:
- https://github.com/tim-hellhake/tasmota-adapter/issues/20
- https://github.com/tim-hellhake/tasmota-adapter/issues/22

I'm closing this now as the original issue is solved.
