### ISSUE TITLE
If all channels are off the Thing should be off

### ISSUE THREAD

**Issue by madb1lly** [tim-hellhake/tasmota-adapter#33]
Hello @tim-hellhake,

First, thank you for making the adapter, very helpful 😃

I'm using the Tasmota adapter with a Sonoff TH16 which I've added an extra output to to control another relay. I am seeing an issue where if both output channels are off the overal Thing is not shown as off. Is it possible to configure the "All" status to = the OR of all the output channels?

Cheers 🙂

**Comment by tim-hellhake** [comment]
Hi @madb1lly :smile: 

Sorry for the late answer.
The adapter uses the `POWER` command to set/get the channel values.
Depending on the number of channels, the command behaves a bit differently.
Could you please send me the output of the `template` command of your TH16 so I can try to replicate the behavior here?

**Comment by madb1lly** [comment]
Hello @tim-hellhake,
No problem on any delay, this is your hobby and I'm not paying you 😆

Template command gives this output:
```
11:00:35 RSL: stat/tasmota_C83947/RESULT = {"NAME":"2 speed extract fan control","GPIO":`[17,255,30,255,255,0,0,0,21,56,3,0,0],"FLAG":0,"BASE":4}
```

I don't know why that line won't format correctly in markdown...?

Cheers 🙂

**Comment by tim-hellhake** [comment]
> I don't know why that line won't format correctly in markdown...?

There is a Backtick just before `[17,...`

I think I need to redesign the `all` OnOffProperty.

**Comment by tim-hellhake** [comment]
> I don't know why that line won't format correctly in markdown...?

There is a Backtick just before `[17,...`

I can reproduce the behavior now.
Especially with the high delay, the other two properties get out of sync.

**Comment by tim-hellhake** [comment]
The issue should be resolved with the latest update.
Did you have a chance to test it?

**Comment by madb1lly** [comment]
Hello @tim-hellhake,

Thanks for the tip on the markdown, well-spotted.

Was your reply about the behaviour relating to this issue or #34?

Cheers 🙂

**Comment by tim-hellhake** [comment]
Only to this issue 😄

**Comment by madb1lly** [comment]
Hi @tim-hellhake,
I meant this which you wrote:

>  I can reproduce the behavior now.
Especially with the high delay, the other two properties get out of sync.

I've not noticed the behaviour in https://github.com/tim-hellhake/tasmota-adapter/issues/33#issue-683386958 again but I only got it working again today! I guess we can close and reopen if I find it happens again.

Cheers 🙂
