### ISSUE TITLE
Outputs become out of sync if Tasmota UI is used

### ISSUE THREAD

**Issue by madb1lly** [tim-hellhake/tasmota-adapter#34]
Hello @tim-hellhake,

I'm noticing an issue where the outputs on the WebThing UI are becoming out of sync with the outputs on the Tasmota UI. This is most obvious if I toggle the outputs on the Tasmota UI, because when I do this there is a delay (probably based on how I configure the adapter, I have it set to 10000ms) between the Tasmota outputs changing and the Gateway catching up with these changes _but_ the delay seems longer than what I set it to.

Also, I have noticed that sometimes the Gateway changes the outputs back to how they were previously set before I changed them in Tasmota, up to several minutes afterwards. This can obviously result in something be re or deenergised, which is not desirable as I'm not expecting it therefore if I'm not in the vicinity of the physical item which is powered I have no way to know this unless I check the Gateway again (and since the outputs are not always in sync, I might not believe what it tells me).

The reason I sometimes use the Tasmota UI is when the Gateway UI is misbehaving, being unusably slow, etc. Sometimes I can click the Tasmota device icon in the Gateway UI and it just changes to ... so I have to go to the Tasmota UI to control the device. Maybe when the Gateway catches up it then sends the request to toggle to the Tasmota device again, which is why it then reverts its setting? But I'm quite sure it does this sometimes without me touching the Tasmota UI.

For info, I increased the delay to 10000ms because with the default setting it seemed to seriously slow down the Gateway.

Cheers 🙂

**Comment by tim-hellhake** [comment]
Hi again :grimacing:,

> the delay seems longer than what I set it to

I increased the delay in my gateway to 10 seconds but the delay was just as expected.

> Sometimes I can click the Tasmota device icon in the Gateway UI and it just changes to ...

Sounds like there is a problem with the communication between gateway and adapter.
Do you have other quirks with your gateway?

Could you please go to the tasmota console (`http://<IP>/cs`) and check the log?
There should be something like this every 10 seconds in your case:
```
RSL: RESULT = {"POWER":"ON"}
RSL: POWER = ON
```
Additionally, you could enable the debug logs in the adapter to check the logs for errors.
You should at least see one entry every time the state changes.
If the adapter picks up a state change from your Tasmota it looks like this:
```
Value of X / On changed to false
```
If you change the state in the gateway you should see the following message:
```
Set value of X / On to false
```

**Comment by tim-hellhake** [comment]
The next update will also log the execution time of the HTTP requests.
Maybe one of the requests is extremely slow and resets the gateway to an old value.

**Comment by madb1lly** [comment]
Hi @tim-hellhake,

Thanks for the suggestions. In the console all I have is:
```
11:05:50 DNS: Query done. MQTT services found 0
11:05:52 DNS: Query done. MQTT services found 0
11:05:53 DNS: Query done. MQTT services found 0
11:05:55 DNS: Query done. MQTT services found 0
11:05:57 DNS: Query done. MQTT services found 0
11:05:59 DNS: Query done. MQTT services found 0
11:06:01 DNS: Query done. MQTT services found 0
11:06:02 DNS: Query done. MQTT services found 0 
```
etc

My tasmota logs are set to info level.

I'm having issues today actuating the Tasmota device via the Gateway, so I'll try and fix that and then test the second part of your suggestion.

Cheers 🙂

**Comment by madb1lly** [comment]
Hi @tim-hellhake,

I had to remove the things, remove the adapter and start again.

I see this in the log:
```
13:17:24 RSL: stat/tasmota_C83947/RESULT = {"POWER1":"OFF"}
13:17:24 RSL: stat/tasmota_C83947/POWER1 = OFF
13:17:24 RSL: stat/tasmota_C83947/RESULT = {"POWER2":"OFF"}
13:17:24 RSL: stat/tasmota_C83947/POWER2 = OFF
13:17:24 RSL: stat/tasmota_C83947/RESULT = {"POWER1":"OFF"}
13:17:24 RSL: stat/tasmota_C83947/POWER1 = OFF
13:17:24 RSL: stat/tasmota_C83947/RESULT = {"POWER2":"OFF"}
13:17:24 RSL: stat/tasmota_C83947/POWER2 = OFF 
```
And I get those other messages in the gateway internal logs as you said.

So that appears to be working. There is definitely some sort of issue which slows down my gateway when I have the UI open, so this could be causing sync problems sometimes.

Cheers 🙂

**Comment by tim-hellhake** [comment]
Can we close the issue or is something missing?

**Comment by madb1lly** [comment]
Hi @tim-hellhake,

I've not noticed the behaviour in https://github.com/tim-hellhake/tasmota-adapter/issues/34#issue-683400122 again but I only got it working again today! I guess we can close and reopen if I find it happens again. 

Cheers 🙂

**Comment by tim-hellhake** [comment]
Let's hope your pi run more smoothly in the future
