### ISSUE TITLE
Plugs detetected as "light" and releted issues

### ISSUE THREAD

**Issue by neil969** [tim-hellhake/tasmota-adapter#5]
I have two UK plugs flashed with Tasmota that are detected quite happily by the adapter.
The issue is that they are detected as "light" ( so the gateway gives them the lightbulb active icon ). In the gateway if you say they are a custom item, the ability to toggle from the main screen goes away.

Is it possible to detect them as power plugs? 
The two plugs are:

-   A Koogeek KLUP1 https://templates.blakadder.com/kogeek_KLUP1.html  (A "standard" Tuya device, by the looks)
     This also reports power consumption - is it possible to have this data available to the gateway? 

- and a Sonoff S26 https://templates.blakadder.com/sonoff_S26.html
    This device seems to be detected as TWO devices.. one is asking for a PIN code- which I don't have , and the other is just "normal". and works... The issue here is that the one asking for a PIN keeps coming up at each search.

**Comment by tim-hellhake** [comment]
> Is it possible to detect them as power plugs?

Sure, I'll change it.

> This device seems to be detected as TWO devices..

This shouldn't be possible unless the device advertises itself under two different names.
Could you please attach the logs?
For every Tasmota device, there should be a message like `Discovered Tasmota at`.

> one is asking for a PIN code

That's very strange.
The adapter is never asking for a pin.

**Comment by tim-hellhake** [comment]
> This also reports power consumption - is it possible to have this data available to the gateway?

I just checked that using the template you supplied.
It should be possible but I have no device to check if it's actually working.
You have to try it for me 😄

**Comment by neil969** [comment]
> 
> 
> > This also reports power consumption - is it possible to have this data available to the gateway?
> 
> I just checked that using the template you supplied.
> It should be possible but I have no device to check if it's actually working.
> You have to try it for me 😄

The Plugs now show as smart plugs ;) 
I removed one and it errored once when I tried to re-add it saying "cannot save" .. The funny thing is , once I tried to search again  ( after power cycling the  Koogeek PLUG) the Sonoff "asking for PIN" device disappeared..  I don't understand it either!!  - maybe there was a database error? 
Now the Koogeek Plug is still not showing any data in it's "thing" I imagine that is where it should be.. I see it if I connect to the device directly by IP address from a browser.. 

Thanks BTW :)

**Comment by tim-hellhake** [comment]
> I removed one and it errored once when I tried to re-add it saying "cannot save" .. The funny thing is , once I tried to search again ( after power cycling the Koogeek PLUG) the Sonoff "asking for PIN" device disappeared..

Can you reproduce this behavior or was it a one-time issue?

> Now the Koogeek Plug is still not showing any data in it's "thing"

The last update only contained the plug fix.
I'm still working on the power data.

**Comment by neil969** [comment]
"Can you reproduce this behavior or was it a one-time issue?"
seems to be a one time thing:) 
Xmas will have me tied up with family things for a few days, but i will continue to "play"  - & Sorry I misinterpreted what you said , and didn't' realise that you were still working on data :)  Sorry about that & thanks for the work you do!

**Comment by neil969** [comment]
OHH!! I just noticed that you committed changes and it is working like MAGIC for the Koogeek Plug now!  :)  - I hadn't looked at it all day ! Brilliant!

**Comment by tim-hellhake** [comment]
> Xmas will have me tied up with family things for a few days

Enjoy your time with the family 🙂.

> misinterpreted what you said , and didn't' realise that you were still working on data :) Sorry about that

No need to apologize 😄.

> OHH!! I just noticed that you committed changes

I always reference the issue in the commit messages so everyone can see the current progress of the issue.

> it is working like MAGIC for the Koogeek Plug now!

Almost like a little Christmas present 😬.
Sometimes a hard reload (Ctrl + Shift + r) of the things page is required to see the changes.
Is there anything left, or can I close the issue?

**Comment by neil969** [comment]
Yes the issue can be closed - Thanks :) 
I got 4 more Koogeeks for Xmas, - flashed them all with Tasmota OTA and it is like magic :)
