### ISSUE TITLE
Support for the inputs & outputs of a Witty Cloud Dev board

### ISSUE THREAD

**Issue by neil969** [tim-hellhake/tasmota-adapter#6]
I have a Witty cloud development board     ( https://templates.blakadder.com/witty_cloud.html ) flashed with Tasmota, and would it be possible to have the inputs & outputs of this device passed back to the gateway? It is detected ( of course!) as a "light" and toggles it's light on and off quite happily 

I actually want to be able to trigger "rules" with feedback from the device.

**Comment by tim-hellhake** [comment]
This seems to be a bit more complicated than the power measuring in https://github.com/tim-hellhake/tasmota-adapter/issues/5 but i'll try.

**Comment by neil969** [comment]
> 
> 
> This seems to be a bit more complicated than the power measuring in #5 but i'll try.

Thanks ;) 
the result seems to be that there are still no properties from it (same as for the KLUP1)  nothing new 
I don't know what I can send you to help - there is only the MAIN log that I know of, and that seems to say little of any interest.. is there Anything else I can do?

**Comment by tim-hellhake** [comment]
> the result seems to be that there are still no properties from it (same as for the KLUP1) nothing new

Sorry for the confusion.
I haven't started working on this yet.
I'll do it after the power measuring is finished.

**Comment by tim-hellhake** [comment]
@neil969
That should work now.
Can you test it?

**Comment by tim-hellhake** [comment]
@neil969 Any news on that?

**Comment by tim-hellhake** [comment]
I'm closing this now.
Please open a new issue if you have any problems.
