### ISSUE TITLE
Configure timers

### ISSUE THREAD

**Issue by PPCM** [tim-hellhake/tasmota-adapter#7]
Using the API of Tasmota, is it possible to add a new feature to enable to configure internal timers of the Tasmota device?

The configuration should be evalaible directly with the device, but with rules too

**Comment by tim-hellhake** [comment]
According to the docs, it shouldn't be a problem.
I'm not sure how to represent the timer as a device, though.
How would you use the timer in a rule?

**Comment by PPCM** [comment]
Great if it is possible
To represent it, a suggestion:
In details of the tasmota device, all 16 timers can displayed with these informations:
- Actions
- Arm
- Repeat
- Style of time setting / action time
- List of days for action

And in rules, for each tasmota device, properties can be completed with list of timers id and actions like:
- Arm
- Disable arm
- Repeat
- Disable repeat

**Comment by tim-hellhake** [comment]
> In details of the tasmota device

I can only expose properties in the detail view of the device.
That would add 80 (16 * 5) additional properties to every device.
The other possibility would be an extra device per timer.
But that means 16 additional devices per tasmota device.
Do you really need to use the built-in timers?
There is `timer` addon available you can use in the rule system of the gateway.

**Comment by tim-hellhake** [comment]
I'm closing this for now.
If you still need it please let me know.
